version: "3"

services:
  giggal-total-back-office-api-green-a:
    image: giggal-people/total-back-office-green-a:latest
    container_name: giggal-people-total-back-office-green-a
    hostname: giggal-people-total-back-office
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - LANG=ko_KR.UTF-8

    build:
      context: ..
      dockerfile: /data/deploy/giggal-total-back-office/deploy/docker/Dockerfile

    restart: unless-stopped
    ports:
      - "8090:8080"
