version: "3"

services:
  giggal-total-back-office-api-blue-b:
    image: giggal-people/total-back-office-blue-b:latest
    container_name: giggal-people-total-back-office-blue-b
    hostname: giggal-people-total-back-office
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - LANG=ko_KR.UTF-8

    build:
      context: ..
      dockerfile: /data/deploy/giggal-total-back-office/deploy/docker/bak-Dockerfile

    restart: unless-stopped
    ports:
      - "8081:8080"
