logging:
  config: classpath:logback-${spring.profiles.active}.xml
  discord:
    webhook-uri: https://discord.com/api/webhooks/1101438455193542687/kO2hLu57TqtTCak19SdhAeeClqowyd83Q24rTEotZTT_LVz4wtOXJikIV6g_iwbfF4Bb

  level:
    root: INFO

    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: INFO
#  logback:
#    rollingpolicy:
#      max-history: 180
#      max-file-size: 100MB

log:
  file:
    path: /var/log/Giggal-Total-Back-Office/*/Error_0.log